behaviors:

  DollAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.001
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      # memory:
      #   sequence_length: 64
      #   memory_size: 128
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.05
        gamma: 0.995
        network_settings:
          hidden_units: 128
          learning_rate: 0.0001
    keep_checkpoints: 100
    checkpoint_interval: 500000
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 10000
